#!/usr/bin/env bash
# Function to handle SIGTERM signal
sigterm_handler() {
    echo "I hate the kill command"
}

# Function to handle SIGINT signal
sigint_handler() {
    echo "Y U no love me?!"
}

# Function to handle SIGQUIT signal
sigquit_handler() {
    echo "Deleting PID file and terminating..."
    rm /var/run/myscript.pid
    exit 0
}

# Trap signals and assign handlers
trap 'sigterm_handler' SIGTERM
trap 'sigint_handler' SIGINT
trap 'sigquit_handler' SIGQUIT

# Write PID to file
echo $$ > /var/run/myscript.pid

# Display message indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 1
done
