#!/usr/bin/env bash
# Write a Bash script
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process is running
if [ -n "$pid" ]
then
    # Send a termination signal to the process
    kill "$pid"
    echo "Process '4-to_infinity_and_beyond' (PID $pid) stopped."
else
    echo "Process '4-to_infinity_and_beyond' is not running."
fi
