#!/usr/bin/env bash
# while loop 10 time
i=0
while [ $i -le 10 ] 
do
    echo "Best School"
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    fi
    ((i++))
done
