#!/usr/bin/env bash
# while loop 10 time
i=0
while [ $i -le 10 ] 
do
	    echo "Best School"
	        if [ $i -eq 9 ]
			    then
				            echo "Hi"
					        fi
						    ((i++))
					    done

