#!/usr/bin/env bash
# while loop 10 time
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations
i=0
while [ $i -le 10 ] 
do
    echo "Best School"
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    fi
    ((i++))
done

