#!/usr/bin/env bash
# ssh_config

Host *
    PasswordAuthentication no
    IdentityFile ~/.ssh/school
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    HostName 34.224.3.235
    User ubuntu